; Room.inc : 部屋
;


; マクロの定義
;

; 部屋
ROOM_ENEMY                      =   0x00
ROOM_ENEMY_0                    =   0x00
ROOM_ENEMY_1                    =   0x01
ROOM_ENEMY_2                    =   0x02
ROOM_ENEMY_3                    =   0x03
ROOM_ENEMY_ENTRY                =   0x04
ROOM_ITEM                       =   0x04
ROOM_COLOR_TABLE                =   0x05
ROOM_LENGTH                     =   0x08

; 外部関数宣言
;

    .globl  _RoomGet

; 外部変数宣言
;

